feat: support dockerfile with multi openssl version
automesh-network/dockerfiles pull request #1
Opened 2024-03-28 13:18 UTC by cavivie

2024-03-28 13:38 UTC, gaoyifan requested changes

2024-03-28 13:38 UTC, gaoyifan commented on .github/workflows/docker-publish.yml
> +        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
buildx 不支援 windows

2024-03-28 13:38 UTC, gaoyifan commented on rust-windows/Dockerfile
> -FROM ghcr.io/automesh-network/dockerfiles:chocolatey
Rust 依赖 openssl 这不太合理。 建议 Rust 作为更底层的镜像， openssl 构建于其上。

2024-03-28 13:38 UTC, gaoyifan commented on vcpkg-windows/Dockerfile
> +RUN choco install visualstudio2022buildtools -y --package-parameters '--quiet --wait --norestart --add Microsoft.Component.MSBuild --add Microsoft.VisualStudio.Component.Windows11SDK.22621 --add Micr
visualstudio2022buildtools 应该放在 rust 镜像中。因为 rust  msvc target 依赖 visual studio build tools.

2024-03-28 13:38 UTC, gaoyifan commented on vcpkg-windows/Dockerfile
> +RUN choco install git strawberryperl -y
git / strawberryperl 是编译 openssl 的依赖，不属于 vcpkg。建议放在 rsxe

2024-03-28 13:38 UTC, gaoyifan commented on vcpkg-windows/Dockerfile
> +FROM ghcr.io/automesh-network/dockerfiles:chocolatey
考虑将 chocolatey 与 vcpkg 打包到一个单一的基础镜像，比如命名为 windows-dev-base.

2024-03-28 13:42 UTC, cavivie commented on vcpkg-windows/Dockerfile
> +RUN choco install visualstudio2022buildtools -y --package-parameters '--quiet --wait --norestart --add Microsoft.Component.MSBuild --add Microsoft.VisualStudio.Component.Windows11SDK.22621 --add Micr
vcpkg构建openssl也依赖于buildtools

2024-03-28 13:43 UTC, cavivie commented on vcpkg-windows/Dockerfile
> +RUN choco install git strawberryperl -y
vcpkg clone依赖于git，这里可以去掉strawberryperl

2024-03-28 13:45 UTC, cavivie commented on vcpkg-windows/Dockerfile
> +FROM ghcr.io/automesh-network/dockerfiles:chocolatey
openssl构建比较耗时的，在未来更改rust版本时，openssl cache失效会重头构建，这里忽略耗时，确实应该在rust镜像之上构建openssl？

2024-03-28 15:32 UTC, gaoyifan requested changes

2024-03-28 15:32 UTC, gaoyifan commented on alrd-windows/Dockerfile
> +RUN choco install git strawberryperl just -y
如果 strawberryperl 是 vcpkg install openssl 的依赖。 这行应该放在安装 openssl 之前？

2024-03-28 15:32 UTC, gaoyifan commented on rsxe-windows/Dockerfile
>  FROM ghcr.io/automesh-network/dockerfiles:rust-windows
如果 rsxe 与 alrd 是一样的。是否考虑直接删掉 rsxe，或用软链接，而不是维护两个一模一样的文件

2024-03-28 15:34 UTC, cavivie commented on alrd-windows/Dockerfile
> +RUN choco install git strawberryperl just -y
vcpkg用的是自己下载的perl，加在这里是为了在vendored场景，无需单独下载perl

2024-03-28 15:44 UTC, cavivie commented on rsxe-windows/Dockerfile
>  FROM ghcr.io/automesh-network/dockerfiles:rust-windows
简单的办法是文件加名称叫一个通用的例如xxx-windows，docker build alrd/rsxe的时候都指定这个文件夹即可，也不用搞什么软链了，不过这个名字叫啥好呢

2024-03-29 03:53 UTC, gaoyifan approved these changes

2024-03-29 03:54 UTC, gaoyifan commented
@cavivie   看起来 CI 没过，像是权限问题

2024-03-29 03:56 UTC, cavivie commented
> @cavivie 看起来 CI 没过，像是权限问题
应该是这行写错了，自定义action获取变量改成这个，仅当非pull request才push
`push: github.event_name != 'pull_request'`  -> 'push: ${{ github.event_name != 'pull_request' }}'

2024-03-29 05:08 UTC, cavivie commented
UDP: 被Javascript坑了：
`if: ${{ x }}` 得改成 `if: ${{ x == true || x == 'true' }}`

https://github.com/actions/runner/issues/1483

2024-03-29 06:33 UTC, merged